name: User Interface Infrastructure changes
description: Issue form for tracking changes to the underlying infrastructure for user interface
title: "[User Interface: Infrastructure]: "
labels: ["ui"]

body:
  - type: markdown
    attributes:
      value: |
        This form is meant for infrastructure changes affecting the UI.         
  - type: input
    id: uiIssueName
    attributes:
      label: Issue Name
      description: Provide a name infrastructure changes
      placeholder: ex. Chakra UI library update
    validations:
      required: True
  - type: textarea
    id: uiIssueDescription
    attributes:
      label: Issue Description
      description: Please describe what changes are needed in order to support the UI
      placeholder: ex- Unit tests are needed to ensure that the UI is working properly
    validations:
      required: true      
  - type: textarea
    id: uiIssueDiscussion
    attributes:
      label: Issue Discussion
      description: Please provide information on when this issue was (or is expected to be) discussed between NIAID, Leidos, and Scripps
      placeholder: ex. The page was discussed at the bi-weekly meeting dated 2023-03-14. It was included in the Technical Report dated 2023-04-10
    validations:
      required: false 
  - type: checkboxes
    id: WBSlink
    attributes:
      label: Related WBS task
      description: Please provide links to any relevant tasks/issues in the WBS/Roadmap repository https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues). 
      options:
        - label: Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
        - label: Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
        - label: Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)
    validations:
      required: false     
  - type: markdown
    attributes:
      value: |
        "## Additional Notes for internal use only." 
  - type: markdown
    attributes:
      value: |
        Submitter, ignore everything below this point.
  - type: checkboxes
    id: uiIssueStatus
    attributes:
      label: For internal use only. Assignee, please select the status of this issue
      options:
        - label: Not yet started
        - label: In progress
        - label: Blocked
        - label: Will not address
    validations:
      required: false
  - type: textarea
    id: uiIssueStatusDescription
    attributes:
      label: Status Description
      description: If the status of this issue is BLOCKED or WILL NOT ADDRESS, please provide more details. Update with links to related GitHub issues here or in comments.
    validations:
      required: false
  - type: checkboxes
    id: uiIssueTaskList
    attributes:
       label: UI change status check list
       description: For internal use only. Use the checklist to provide updates on the status of the request
       options:
         - label: This ui infrastructure change has yet to be discussed between NIAID, Scripps, Leidos
         - label: This ui infrastructure change has been discussed/reported between NIAID, Scripps, Leidos
         - label: This ui infrastructure change has been mocked up
         - label: This ui infrastructure change has been implemented on Dev
         - label: This ui infrastructure change has been approved for Staging
         - label: This ui infrastructure change has been implemented on Staging
         - label: This ui infrastructure change has been approved for Production
         - label: This ui infrastructure change has been implemented on Production
