export const mockBiothingsChildrenApiResponse = {
  children: [
    {
      id: '9592',
      label: 'gorilla',
      taxonId: '9592',
      ontologyName: 'ncbitaxon',
      hasChildren: true,
      counts: {}, // Empty counts initially
    },
    {
      id: '9596',
      label: 'pan',
      taxonId: '9596',
      ontologyName: 'ncbitaxon',
      hasChildren: true,
      counts: {},
    },
    {
      id: '9605',
      label: 'homo',
      taxonId: '9605',
      ontologyName: 'ncbitaxon',
      hasChildren: true,
      counts: {},
    },
  ],
  pagination: {
    hasMore: false,
    totalElements: 3,
  },
};

export const mockBiothingsChildrenPaginatedApiResponse = {
  children: [
    {
      id: '2686027',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2686027',
      label: 'ancyromonadida',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2686027',
    },
    {
      id: '2608240',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2608240',
      label: 'crums',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2608240',
    },
    {
      id: '2598132',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2598132',
      label: 'rhodelphea',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2598132',
    },
    {
      id: '2489521',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2489521',
      label: 'hemimastigophora',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2489521',
    },
    {
      id: '2795258',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2795258',
      label: 'malawimonadida',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2795258',
    },
    {
      id: '1401294',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_1401294',
      label: 'breviatea',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '1401294',
    },
    {
      id: '554296',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_554296',
      label: 'apusozoa',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '554296',
    },
    {
      id: '38254',
      commonName: 'glaucocystophytes',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_38254',
      label: 'glaucocystophyceae',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '38254',
    },
    {
      id: '2683617',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2683617',
      label: 'eukaryota incertae sedis',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2683617',
    },
    {
      id: '61964',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_61964',
      label: 'environmental samples',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '61964',
    },
    {
      id: '42452',
      commonName: '',
      hasChildren: false,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_42452',
      label: 'unclassified eukaryotes',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '42452',
    },
    {
      id: '3027',
      commonName: 'cryptomonads',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_3027',
      label: 'cryptophyceae',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '3027',
    },
    {
      id: '2608109',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2608109',
      label: 'haptista',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2608109',
    },
    {
      id: '2611341',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2611341',
      label: 'metamonada',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2611341',
    },
    {
      id: '2763',
      commonName: 'red algae',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2763',
      label: 'rhodophyta',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2763',
    },
    {
      id: '554915',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_554915',
      label: 'amoebozoa',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '554915',
    },
    {
      id: '2698737',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2698737',
      label: 'sar',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2698737',
    },
    {
      id: '2611352',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_2611352',
      label: 'discoba',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '2611352',
    },
    {
      id: '33090',
      commonName: 'green plants',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_33090',
      label: 'viridiplantae',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: false,
      },
      taxonId: '33090',
    },
    {
      id: '33154',
      commonName: '',
      hasChildren: true,
      iri: 'http://purl.obolibrary.org/obo/NCBITaxon_33154',
      label: 'opisthokonta',
      ontologyName: 'ncbitaxon',
      parentTaxonId: '2759',
      state: {
        opened: false,
        selected: true,
      },
      taxonId: '33154',
    },
  ],
  pagination: {
    hasMore: true,
    numPage: 0,
    totalPages: 2,
    totalElements: 21,
  },
};
