import type {NextPage} from 'next';
import Head from 'next/head';
import NavigationBar from 'src/components/navigation';
import navItems from 'configs/navigation.json';
import PageContainer from 'src/components/page-container';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NDE Portal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavigationBar navItems={navItems.routes} />

      <PageContainer>
        <h1>Main</h1>
      </PageContainer>
    </div>
  );
};

export default Home;
