import type {NextPage} from 'next';
import Head from 'next/head';
import PageContainer from 'src/components/page-container';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NDE Portal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PageContainer hasNavigation>
        {/* <Box
          w={'100%'}
          backgroundImage={'url(/assets/bg-option.png)'}
          backgroundSize={'cover'}
        >
          <h1>Main</h1>
        </Box> */}
        {/* <Image src={'/assets/bg-option.png'} w='100%' h='100%' /> */}
      </PageContainer>
    </div>
  );
};

export default Home;
