import SITE_CONFIG from 'configs/site.config.json';
import { SiteConfig } from 'src/components/page-container/types';
import { EndpointStatus } from './status-helpers';
import { PAGE_ENDPOINTS } from './page-endpoints.generated';

export type PageStatus = 'operational' | 'degraded' | 'impacted';

export interface PageDependency {
  label: string;
  path: string;
  endpoints: string[];
}

const config = SITE_CONFIG as SiteConfig;

/**
 * Resolve the display label for a page path from site.config.json.
 * Falls back: nav.label → seo.title → formatted path.
 */
function resolveLabel(
  path: string,
  page: (typeof config.pages)[string] | undefined,
): string {
  if (page?.nav?.label) return page.nav.label;
  if (page?.seo?.title) return page.seo.title;
  return path
    .replace(/^\//, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

/**
 * Page list and endpoints are auto-generated by scripts/generate-page-endpoints.ts.
 * Labels are resolved from site.config.json.
 */
export const PAGE_DEPENDENCIES: PageDependency[] = Object.entries(
  PAGE_ENDPOINTS,
)
  .map(([path, endpoints]) => ({
    path,
    label: resolveLabel(path, config.pages[path]),
    endpoints,
  }))
  .sort((a, b) => a.label.localeCompare(b.label));

/**
 * Derive a single page's status from the statuses of the endpoints it depends on.
 */
export function getPageStatus(
  depEndpoints: string[],
  endpointStatuses: Record<string, EndpointStatus | 'loading'>,
): PageStatus | 'loading' {
  if (depEndpoints.length === 0) return 'operational';

  const statuses = depEndpoints.map(id => endpointStatuses[id] ?? 'loading');

  if (statuses.some(s => s === 'loading')) return 'loading';
  if (statuses.some(s => s === 'down')) return 'impacted';
  if (statuses.some(s => s === 'degraded')) return 'degraded';
  return 'operational';
}

/**
 * Derive the overall status across all pages.
 */
export function getOverallPagesStatus(
  endpointStatuses: Record<string, EndpointStatus | 'loading'>,
): PageStatus | 'loading' {
  const pageStatuses = PAGE_DEPENDENCIES.map(p =>
    getPageStatus(p.endpoints, endpointStatuses),
  );

  if (pageStatuses.every(s => s === 'loading')) return 'loading';
  if (pageStatuses.some(s => s === 'impacted')) return 'impacted';
  if (pageStatuses.some(s => s === 'degraded')) return 'degraded';
  return 'operational';
}
