import MetadataFields from 'configs/resource-fields.json';

type Field = typeof MetadataFields[number];

/****
 * Overlapping or unnecessary fields.
 * Based On:
 * https://docs.google.com/spreadsheets/d/1YoCzJ85px-wuOEgOvz-XlVICIqataBwimLuUE4-eV2s/edit#gid=291523994
 */
const UNUSED_FIELDS = [
  'abstract',
  'aggregateRating.ratingCount',
  'aggregateRating.ratingValue',
  'aggregateRating.reviewAspect',
  'aggregateRating.@type',
  'alternateName',
  'applicationSubCategory.identifier',
  'applicationSubCategory.@type',
  'applicationSubCategory.url',
  'author.affiliation.sameAs',
  'author.affiliation.@type',
  'author.email',
  'author.role',
  'author.title',
  'author.@type',
  'author.url',
  'availableOnDevice',
  'citation.abstract',
  'citation.author.@type',
  'citation.citation',
  'citation.description',
  'citation.pagination',
  'citation.@type',
  'citation.url',
  'citation.volumeNumber',
  'citedBy.abstract',
  'citedBy.author.familyName',
  'citedBy.author.givenName',
  'citedBy.author.name',
  'citedBy.author.@type',
  'citedBy.citation',
  'citedBy.datePublished',
  'citedBy.description',
  'citedBy.identifier',
  'citedBy.issueNumber',
  'citedBy.journalName',
  'citedBy.journalNameAbbrev',
  'citedBy.pagination',
  'citedBy.@type',
  'citedBy.url',
  'citedBy.volumeNumber',
  'codeRepository',
  'contentSize',
  'contentUrl',
  'contributor.@id',
  'contributor.affiliation',
  'contributor.@type',
  'curatedBy.@type',
  'curatedBy.url',
  'curatedBy.versionDate',
  'discussionUrl',
  'distribution.@id',
  'distribution.contentSize',
  'distribution.contentUrl',
  'distribution.dateCreated',
  'distribution.datePublished',
  'distribution.description',
  'distribution.name',
  'distribution.@type',
  'featureList',
  'funding.description',
  'funding.funder.class',
  'funding.funder.role',
  'funding.funder.url',
  'funding.url',
  'spatialCoverage.@type',
  'spatialCoverage.geo',
  'spatialCoverage.geo.@type',
  'spatialCoverage.geo.latitude',
  'spatialCoverage.geo.latitude',
  'spatialCoverage.geo.longitude',
  'spatialCoverage.geo.longitude',
  'spatialCoverage.geo.@type',
  'hasPart.@id',
  'hasPart.encodingFormat',
  'hasPart.@type',
  'hasPart.url',
  'healthCondition.url',
  'inLanguage.alternateName',
  'inLanguage.@type',
  'input.identifier',
  'input.@type',
  'interactionStatistic.interactionType',
  'interactionStatistic.@type',
  'interactionStatistic.userInteractionCount',
  'isBasedOn.abstract',
  'isBasedOn.additionalType.url',
  'isBasedOn.citation',
  'isBasedOn.datePublished',
  'isBasedOn.doi',
  'isBasedOn.pmid',
  'isBasedOn.@type',
  'isBasedOn.url',
  'isBasisFor.identifier',
  'isBasisFor.name',
  'isBasisFor.url',
  'isPartOf.@id',
  'isPartOf.identifier',
  'isPartOf.name',
  'isPartOf.@type',
  'isPartOf.url',
  'isRelatedTo.hasPart.identifier',
  'isRelatedTo.hasPart.@type',
  'isRelatedTo.relationship',
  'isRelatedTo.includedInDataCatalog.name',
  'isRelatedTo.includedInDataCatalog.@type',
  'isRelatedTo.includedInDataCatalog.url',
  'isRelatedTo.includedInDataCatalog.versionDate',
  'isRelatedTo.@type',
  'isSimilarTo.identifier',
  'isSimilarTo.name',
  'isSimilarTo.relationship',
  'isSimilarTo.includedInDataCatalog.name',
  'isSimilarTo.includedInDataCatalog.@type',
  'isSimilarTo.includedInDataCatalog.url',
  'isSimilarTo.includedInDataCatalog.versionDate',
  'isSimilarTo.@type',
  'mainEntityOfPage',
  'measurementTechnique.url',
  'nctid',
  'output.identifier',
  'output.@type',
  'infectiousAgent.url',
  'temporalCoverage.temporalInterval.@type',
  'temporalCoverage.temporalInterval.duration',
  'temporalCoverage.temporalInterval.name',
  'relationship',
  'sameAs',
  'softwareAddOn.identifier',
  'softwareHelp.name',
  'softwareHelp.url',
  'sourceInfo',
  'sourceInfo.description',
  'sourceInfo.identifier',
  'sourceInfo.name',
  'sourceInfo.schema',
  'sourceInfo.schema.field',
  'sourceInfo.url',
  'sourceInfo.url',
  'sdPublisher.identifier',
  'sdPublisher.@type',
  'sdPublisher.url',
  'includedInDataCatalog.@type',
  'includedInDataCatalog.url',
  'includedInDataCatalog.versionDate',
  'species',
  'species.additionalType',
  'species.additionalType.name',
  'species.additionalType.url',
  'species.identifier',
  'species.url',
  'thumbnailUrl',
  'thumbnailUrl',
  'topicCategory',
  'topicCategory.curatedBy',
  'topicCategory.curatedBy.name',
  'topicCategory.curatedBy.url',
  'topicCategory.url',
  'url',
  'usageInfo',
  'usageInfo.description',
  'usageInfo.name',
  'usageInfo.url',
  'version',
];

// Filter out fields we want to remove from field select.
export const filterFields = (field: Field) => {
  return (
    !field.property.toLowerCase().includes('haspart') &&
    !field.property.toLowerCase().includes('email') &&
    !field.property.toLowerCase().includes('url') &&
    !field.property.toLowerCase().includes('mainEntityOfPage') &&
    !(field.property.includes('@') && field.property !== '@type') &&
    field.type !== 'object' &&
    field.count >= 100 &&
    !UNUSED_FIELDS.includes(field.property)
  );
};

export const transformFieldName = (field: Field) => {
  if (field.property === 'author.identifier') {
    return 'Author ORCID ID';
  } else if (field.property === 'citation.name') {
    return 'Citation Title';
  } else if (field.name.toLowerCase().includes('distribution')) {
    return field.name.replace('Distribution', 'File - ');
  }
  return field.name;
};
