name: Staging Deployment of NDE-PORTAL Webapp

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: env
      - name: build website
        run: yarn run build:staging
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
      - name: install additional packages for broken links test
        run: yarn add puppeteer axios jest
      - name: start react app
        run: yarn start &
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
      - name: Run tests and send Slack notification
        run: npm test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: sync s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.NDE_PORTAL_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          README_API_KEY: ${{ secrets.README_API_KEY }}
          SOURCE_DIR: './out'
          DEST_DIR: 'staging'
      - name: invalidate cloudfront distribution and wait for completion
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        env:
          DISTRIBUTION_ID: ${{ secrets.STAGING_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
